package com.core.designsystem.theme
import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0XFFFF7043)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFFFD4C6)
internal val md_theme_light_onPrimaryContainer = Color(0xFF282828)
internal val md_theme_light_primaryFixed = Color(0xFFFFE2D9)
internal val md_theme_light_primaryFixedDim = Color(0xFFFFC5B4)
internal val md_theme_light_onPrimaryFixed = Color(0xFF141414)
internal val md_theme_light_onPrimaryFixedVariant = Color(0xFF33160D)
internal val md_theme_light_secondary = Color(0xFFFFD54F)
internal val md_theme_light_onSecondary = Color(0xFF141414)
internal val md_theme_light_secondaryContainer = Color(0xFFFFF3CA)
internal val md_theme_light_onSecondaryContainer = Color(0xFF332B10)
internal val md_theme_light_secondaryFixedDim = Color(0xFFFFEFB9)
internal val md_theme_light_secondaryFixed = Color(0xFFFFF7DC)
internal val md_theme_light_onSecondaryFixed = Color(0xFF332B10)
internal val md_theme_light_onSecondaryFixedVariant = Color(0xFF4D4018)
internal val md_theme_light_tertiary = Color(0xFFFF4081)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFFC6D9)
internal val md_theme_light_onTertiaryContainer = Color(0xFF330D1A)
internal val md_theme_light_tertiaryFixed = Color(0xFFFFD9E6)
internal val md_theme_light_tertiaryFixedDim = Color(0xFFFFB3CC)
internal val md_theme_light_onTertiaryFixed = Color(0xFF330D1A)
internal val md_theme_light_onTertiaryFixedVariant = Color(0xFF4D1326)
internal val md_theme_light_error = Color(0xFFE33338)
internal val md_theme_light_errorContainer = Color(0xFFFCE9E9)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF881E21)
internal val md_theme_light_background = Color(0xFFFFFFFF)
internal val md_theme_light_onBackground = Color(0xFF282828)
internal val md_theme_light_outline = Color(0xFF797979)
internal val md_theme_light_inverseSurface = Color(0xFF2C2C2C)
internal val md_theme_light_inverseOnSurface = Color(0xFFFAFAFA)
internal val md_theme_light_inversePrimary = Color(0xFFFFA88E)
internal val md_theme_light_shadow = Color(0xFF282828)
internal val md_theme_light_outlineVariant = Color(0xFFC8C8C8)
internal val md_theme_light_scrim = Color(0xFF282828)
internal val md_theme_light_surface = Color(0xFFFAFAFA)
internal val md_theme_light_onSurface = Color(0xFF282828)
internal val md_theme_light_onSurfaceVariant = Color(0xFF434343)
internal val md_theme_light_surfaceContainerHighest = Color(0xFFEAEAEA)
internal val md_theme_light_surfaceContainerHigh = Color(0xFFF2F2F2)
internal val md_theme_light_surfaceContainer = Color(0xFFEFEFEF)
internal val md_theme_light_surfaceContainerLow = Color(0xFFFAFAFA)
internal val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
internal val md_theme_light_surfaceDim = Color(0xFFEFEFEF)
internal val md_theme_light_surfaceBright = Color(0xFFF4F4F4)

internal val md_theme_light_disable_primary = Color(0x1FFF7043)
internal val md_theme_light_disable_primary_content = Color(0x61FF7043)
internal val md_theme_light_disable_button = Color(0x1F28281F)
internal val md_theme_light_disable_button_content = Color(0x6128281F)

val colorOnSurfaceVariant2 = Color(0xFF656565)
val colorOnSurfaceVariant3 = Color(0xFFDDDDDD)